In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('../data/lizcore_gym_data.csv')

In [31]:
def eda_preliminar (df):
  
  display(df.sample(5))
  print('------------------------')
  print('DIMENSIONES')
  print(f'nuestro conjunto de datos presenta {df.shape[0]} filas y {df.shape[1]} columnas')
  print('------------------------')
  print('INFO')
  display(df.info())
  print('------------------------')
  print('NULOS')
  display(df.isnull().sum()/df.shape[0]*100)
  print('------------------------')
  print('DUPLICADOS')
  print(f'tenemos un total de {df.duplicated().sum()} duplicados')
  print('------------------------')
  print('FRECUENCIA CATEGORICAS')
  # Mostrar todo sin truncar mientras dure este with
  with pd.option_context(
    "display.max_rows", None,        # no recortar filas
    "display.max_colwidth", None,    # no recortar texto
    "display.width", 0               # ajustar al ancho
):
    for col in df.select_dtypes(include="object").columns:
        # normaliza: quita espacios, unifica NaN
        s = df[col].astype(str).str.strip()
        s = s.replace({"": np.nan, "nan": np.nan, "None": np.nan})

        vc = s.value_counts(dropna=False)  # incluye NaN
        print(f"\n==== {col.upper()} (unique={vc.size}) ====")
        display(vc.to_frame("count"))

In [32]:
eda_preliminar(df)

,date,user_id,route_id,grade,attempts,success,session_duration_min
21,2025-01-02,58,26,6b,2.0,1,94.470222
221,2025-01-25,23,3,5c,3.0,1,67.529676
165,2025-02-16,36,25,6b,1.0,1,88.314811
242,2025-01-24,7,29,5a,4.0,0,125.641566
442,2025-01-06,38,27,6a,3.0,1,67.538789

------------------------
DIMENSIONES
nuestro conjunto de datos presenta 500 filas y 7 columnas
------------------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  500 non-null    object
 1   user_id               500 non-null    int64
 2   route_id              500 non-null    int64
 3   grade                 500 non-null    object
 4   attempts              475 non-null    float64
 5   success               500 non-null    int64
 6   session_duration_min  474 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 27.5+ KB

None

------------------------
NULOS

date                    0.0
user_id                 0.0
route_id                0.0
grade                   0.0
attempts                5.0
success                 0.0
session_duration_min    5.2
dtype: float64

------------------------
DUPLICADOS
tenemos un total de 0 duplicados
------------------------
FRECUENCIA CATEGORICAS

==== DATE (unique=60) ====

            count
date
2025-03-01     17
2025-02-02     17
2025-01-24     15
2025-02-04     15
2025-01-02     13
2025-02-13     12
2025-02-01     12
2025-02-08     12
2025-02-21     11
2025-01-28     11
2025-02-18     11
2025-01-03     11
2025-02-17     11
2025-01-25     10
2025-02-11     10
2025-01-26     10
2025-02-28     10
2025-01-08     10
2025-02-09      9
2025-01-29      9
2025-02-06      9
2025-01-09      9
2025-02-24      9
2025-02-23      9
2025-01-11      8
2025-01-23      8
2025-02-22      8
2025-01-27      8
2025-01-22      8
2025-01-15      8
2025-01-01      8
2025-02-10      8
2025-02-20      8
2025-01-07      8
2025-02-05      7
2025-01-30      7
2025-01-18      7
2025-01-20      7
2025-01-14      7
2025-01-04      7
2025-01-21      7
2025-02-27      7
2025-02-26      7
2025-02-16      7
2025-01-06      7
2025-01-16      7
2025-01-17      7
2025-01-19      6
2025-02-14      6
2025-02-19      5
2025-01-12      5
2025-02-07      5
2025-02-15      5
2025-01-05      5
2025-01-13      4
2025-02-03      4
2025-02-25      4
2025-01-31      4
2025-02-12      3
2025-01-10      1

==== GRADE (unique=7) ====

       count
grade
5c        82
6c        79
5a        75
6a        75
7b        68
7a        65
6b        56